### ISSUE TITLE
Use DLF link as main livestream source?

### ISSUE THREAD

**Issue by adcxyz** [futurevoices/FV_web#44]
There are two radio streams: 
the gencomp stream at https://gencomp.medienhaus.udk-berlin.de:8443/future.mp3
the DLF stream at https://dradio-edge-3099-dus-ts-cdn.cast.addradio.de/dradio/event/live/mp3/128/stream.mp3

Both should be linked on the FV webpage; 
Pros / Cons for choosing one of them as main stream source:
DLF + has a fallback system, so more reliable than the gencomp stream. 
DLF - when there are bad problems, machine is tricky to access physically
gencomp + better level, more like most webradios, (DLF is ca 6dB softer)
gencomp - when internet@adc is slow, stream upload stutters

**Comment by vin-ni** [comment]
Done :)
